alias gc="git commit"
alias gca="git commit --amend"
alias ga="git add"
alias gau="git add -u"
alias gap="git add -up"
alias gb="git branch"
alias gch="git checkout"
alias gp="git push"
alias gpf="git push -f"

alias v="nvim"
