[[plugins]]
repo="neovim/nvim-lsp"

[[plugins]]
repo="mfussenegger/nvim-jdtls"

[plugins.ftplugin]
# java="echo 'why?'"
lua_java='''
vim.notify("jdtls!")
lsp_dir = '/'
root_dir = vim.fs.root(0, {"gradlew", 'mvnw'})
local config = {
        cmd = {'eclipse-jdt-ls', '-data', vim.fs.basename(root_dir)},
	root_dir = root_dir,
 }
require('jdtls').start_or_attach(config)
'''
