[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "nvim-lua/plenary.nvim"
name = "plenary"

[[plugins]]
repo = "nvim-telescope/telescope.nvim"
name = "telescope"
depends = "plenary"

[[plugins]]
repo = "nvim-telescope/telescope-file-browser.nvim"
depends = "telescope"

[[plugins]]
repo = "vim-skk/skkeleton"

[[plugins]]
repo = "Al0den/notion.nvim"
depends = "telescope"
