[[plugins]]
repo= "tpope/vim-commentary"

[[plugins]]
repo= "nvim-lua/plenary.nvim"
name = "plenary"

[[plugins]]
repo= "nvim-telescope/telescope.nvim"
depends = "plenary"

[[plugins]]
repo= "vim-skk/skkeleton"
